### ISSUE TITLE
http://69.127.23.128:4567/

### ISSUE THREAD

**Issue by h4xrOx** [2bRule34/h4xr0x#1]
![image](https://user-images.githubusercontent.com/65768277/121772582-08680880-cb2b-11eb-9afa-11c9c835e75f.png)
![image](https://user-images.githubusercontent.com/65768277/121772596-1cac0580-cb2b-11eb-8b62-ecc65d7e9e18.png)

**Comment by h4xrOx** [comment]
![image](https://user-images.githubusercontent.com/65768277/121772884-2b93b780-cb2d-11eb-9c2f-1b93a5e2cf83.png)

**Comment by 2bUwU** [comment]
not me. not my ip. not my shit. i didnt do anything besides post admin logs

**Comment by 2bUwU** [comment]
i didnt do it to your yt. was this kid ik thats like 7 lmao. I didnt have any association with h4xr0x.com yet I still get banned. so really the only thing i did wrong was post admin logs that members already had downloaded. its whatever though. your server your rules.
